# Start configuration added by Zim install {{{
#
# User configuration sourced by all invocations of the shell
#

# Define Zim location
: ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}
# }}} End configuration added by Zim install

export ANDROID_HOME=$HOME/Library/Android/sdk
export FLUTTER_ROOT=$HOME/Library/Flutter
export PATH="$PATH:$FLUTTER_ROOT/bin:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools"
# export LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
# export GDK_SCALE=2

